on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Installing git
      run: |    
         apt-get update && apt-get install -y unzip git

    - name: Install composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        composer self-update -- 2.1.1
        composer install --ignore-platform-req=ext-sodium
 
    - name: Run Testsuite
      run: vendor/bin/phpcs -i
