on:
  pull_request:
    types:
      - "**"
name: CI
jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
    steps:
     - uses: actions/checkout@v2
     
     - name: Installing git && curl && jq
       run: |    
          apt-get update && apt-get install -y unzip git && apt-get install -y jq
     - name: Install composer dependencies
       run: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         composer self-update -- 2.1.1
         composer install --ignore-platform-req=ext-sodium
     - name: Retrieve diff content for PR files to the phpcs
       run: |
          git config --global --add safe.directory /__w/PR/PR
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-only --diff-filter=ACM | xargs vendor/bin/phpcs --error-severity=1 --warning-severity=0 --standard=Magento2
 
