name: CI
on:
  pull_request:
    types: [opened]
jobs:
    runs-on: ubuntu-latest
    container:
      image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
  
    steps:
    - name: Install composer dependencies
      run: |
        composer install --ignore-platform-req=ext-sodium
 
    - name: Run Magento coding standard 
      run: vendor/bin/phpcs -i
