on:
  pull_request:
    branches:
      - '**'
name: CI
jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:7.4-fpm-1.3.5
    steps:
     - uses: actions/checkout@v2
     
     - name: Installing git 
       run: |    
          apt-get update && apt-get install -y unzip git 
     - name: Install composer dependencies
       run: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         composer self-update -- 2.2.21
         composer install --ignore-platform-req=ext-sodium
     - name: Retrieve diff content for PR files to the phpcs
       run: |
               pwd
               cd /__w/PR/PR
               pwd
               git config --global --add safe.directory /__w/PR/PR
               git fetch --all
               git branch -a | sed -n 's/remotes\/origin\/\(.*\)/\1/p' | xargs -I {} git checkout {}
               git pull --all
               git branch
               echo "Source Branch: ${{ github.event.pull_request.head.ref }}"
               git checkout ${{ github.event.pull_request.head.ref }}
               vendor/bin/phpcs -i
               git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-only --diff-filter=ACM | xargs vendor/bin/phpcs --error-severity=1 --warning-severity=0 --standard=Magento2
