name: CI

on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Composer
        uses: php-actions/composer@v5
        with:
          php_version: 7.2
