on:
  pull_request:
    types:
      - "**"
name: CI
jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
    steps:
     - uses: actions/checkout@v2
     
     - name: Installing git && curl && jq
       run: |    
          apt-get update && apt-get install -y unzip git && apt-get install -y jq
     - name: Install composer dependencies
       run: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         composer self-update -- 2.1.1
         composer install --ignore-platform-req=ext-sodium
     - name: Retrieve diff content for PR files
       id: pr-diff
       run: |
         diff_content=""
         files=$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
         "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
         | jq -r '.[] | .filename')
         for file in $files; do
         diff=$(git diff --no-index /dev/null "$file")
         diff_content+="Diff for file: $file\n$diff\n\n"
         done
         echo "$diff_content" > pr_diff.txt

     - name: Display PR diff content
       run: |
         cat pr_diff.txt

     - name: Run PHPCS
       run: |
           cat pr_diff.txt | xargs vendor/bin/phpcs --error-severity=1 --warning-severity=0 --standard=Magento2

 
