on:
  pull_request:
    types:
      - "**"
name: CI
jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
    steps:
     - uses: actions/checkout@v2
     
     - name: Installing git && curl && jq
       run: |    
          apt-get update && apt-get install -y unzip git && apt-get install -y jq
     - name: Install composer dependencies
       run: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         composer self-update -- 2.1.1
         composer install --ignore-platform-req=ext-sodium
     - name: Retrieve committed files in PR
       id: pr-files
       run: |
          git config --global --add safe.directory /__w/PR/PR
          files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)
          echo "$files" > committed_files.txt

     - name: Run PHPCS
       run: |
           cat committed_files.txt | xargs vendor/bin/phpcs --error-severity=1 --warning-severity=0 --standard=Magento2

 
