name: Build and Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:7.4-fpm-1.3.0
    steps:
      - uses: actions/checkout@v2
     
      - name: Installing git 
        run: |    
          apt-get update && apt-get install -y unzip git 
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          
          
      - name: Install dependencies
        run: composer install --ignore-platform-req=ext-sodium
        
      - name: Check PHP version
        run: php -m
        
      - name: Check Composer version
        run: composer -V
        
      - name: Display commit information
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.event.pull_request.base.sha }}
          
      - name: Run PHP Code Sniffer
        run: |
          vendor/bin/phpcs -i
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-only --diff-filter=ACM | xargs vendor/bin/phpcs --error-severity=1 --warning-severity=0 --standard=Magento2
